# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whois',
            old_name='_internal_cache_date',
            new_name='internal_cache_date',
        ),
    ]
