# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Registrar'),
        ),
    ]
