# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20161127_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='domain',
            name='registrant',
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Registrant'),
        ),
    ]
