# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20161127_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrant',
            old_name='registrant',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='registrar',
            new_name='name',
        ),
    ]
